# Generated by Django 6.0.7 on 2026-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('from_name', models.CharField(max_length=50)),
                ('from_address_line_1', models.CharField(max_length=50)),
                ('from_address_line_2', models.CharField(blank=True, max_length=50)),
                ('from_address_city', models.CharField(max_length=50)),
                ('from_address_region', models.CharField(max_length=50)),
                ('from_address_post_code', models.CharField(max_length=50)),
                ('from_country', models.CharField(max_length=50)),
                ('to_name', models.CharField(max_length=50)),
                ('to_address_line_1', models.CharField(max_length=50)),
                ('to_address_line_2', models.CharField(blank=True, max_length=50)),
                ('to_address_city', models.CharField(max_length=50)),
                ('to_address_region', models.CharField(max_length=50)),
                ('to_address_post_code', models.CharField(max_length=50)),
                ('to_country', models.CharField(max_length=50)),
                ('recipient_phone', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('scheduled_delivery', models.DateTimeField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
